version: "3.9"

services:
  db:
    image: postgres:15
    container_name: porter_postgres
    restart: always
    environment:
      POSTGRES_USER: porter
      POSTGRES_PASSWORD: porterpassword
      POSTGRES_DB: porterdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
